# Dec. 24, 2020
# JOB: python train_model.py --net_type Unet --backbone efficientnetb0 --pre_train True --batch_size 14 --dim 512 --epoch 2400 --lr 5e-4 --dataset cycle_736x752 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_model.py --net_type Unet --backbone efficientnetb1 --pre_train True --batch_size 14 --dim 512 --epoch 2400 --lr 5e-4 --dataset cycle_736x752 --gpu 1 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_model.py --net_type Unet --backbone efficientnetb2 --pre_train True --batch_size 14 --dim 512 --epoch 2400 --lr 5e-4 --dataset cycle_736x752 --gpu 2 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4
# JOB: python train_model.py --net_type Unet --backbone efficientnetb3 --pre_train True --batch_size 14 --dim 512 --epoch 2400 --lr 5e-4 --dataset cycle_736x752 --gpu 3 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4

# JOB: python train_model.py --net_type Unet --backbone efficientnetb4 --pre_train True --batch_size 8 --dim 512 --epoch 2400 --lr 5e-4 --dataset cycle_736x752 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_model.py --net_type Unet --backbone efficientnetb5 --pre_train True --batch_size 8 --dim 512 --epoch 2400 --lr 5e-4 --dataset cycle_736x752 --gpu 1 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_model.py --net_type Unet --backbone efficientnetb6 --pre_train True --batch_size 6 --dim 512 --epoch 2400 --lr 5e-4 --dataset cycle_736x752 --gpu 2 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4
# JOB: python train_model.py --net_type Unet --backbone efficientnetb7 --pre_train True --batch_size 4 --dim 512 --epoch 2400 --lr 5e-4 --dataset cycle_736x752 --gpu 3 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4

# Jan 11, 2021
# JOB: python train_model.py --net_type Unet --backbone efficientnetb4 --pre_train True --batch_size 8 --dim 512 --epoch 2400 --lr 5e-4 --dataset cycle_736x752 --gpu 0 --loss focal+dice --filters 128 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4
# JOB: python train_model.py --net_type Unet --backbone efficientnetb5 --pre_train True --batch_size 8 --dim 512 --epoch 2400 --lr 5e-4 --dataset cycle_736x752 --gpu 1 --loss focal+dice --filters 128 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_model.py --net_type Unet --backbone efficientnetb6 --pre_train True --batch_size 6 --dim 512 --epoch 2400 --lr 5e-4 --dataset cycle_736x752 --gpu 2 --loss focal+dice --filters 128 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4
# JOB: python train_model.py --net_type Unet --backbone efficientnetb7 --pre_train True --batch_size 4 --dim 512 --epoch 2400 --lr 5e-4 --dataset cycle_736x752 --gpu 3 --loss focal+dice --filters 128 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4

# Jan 16, 2021
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb0 --pre_train True --batch_size 14 --dim 512 --epoch 2400 --lr 5e-4 --dataset viability_832x832 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb1 --pre_train True --batch_size 14 --dim 512 --epoch 2400 --lr 5e-4 --dataset viability_832x832 --gpu 1 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb2 --pre_train True --batch_size 14 --dim 512 --epoch 2400 --lr 5e-4 --dataset viability_832x832 --gpu 2 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb3 --pre_train True --batch_size 14 --dim 512 --epoch 2400 --lr 5e-4 --dataset viability_832x832 --gpu 3 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4

# JOB: python train_viability.py --net_type Unet --backbone efficientnetb4 --pre_train True --batch_size 8 --dim 512 --epoch 2400 --lr 5e-4 --dataset viability_832x832 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb5 --pre_train True --batch_size 8 --dim 512 --epoch 2400 --lr 5e-4 --dataset viability_832x832 --gpu 1 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb6 --pre_train True --batch_size 6 --dim 512 --epoch 2400 --lr 5e-4 --dataset viability_832x832 --gpu 2 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb7 --pre_train True --batch_size 4 --dim 512 --epoch 2400 --lr 5e-4 --dataset viability_832x832 --gpu 3 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4

# JOB: python train_viability.py --net_type AtUnet --backbone efficientnetb0 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 5e-4 --dataset viability_832x832 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type AtUnet --backbone efficientnetb1 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 5e-4 --dataset viability_832x832 --gpu 1 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type AtUnet --backbone efficientnetb2 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 5e-4 --dataset viability_832x832 --gpu 2 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4
# JOB: python train_viability.py --net_type AtUnet --backbone efficientnetb3 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 5e-4 --dataset viability_832x832 --gpu 3 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4

# Jan 19, 2021
# JOB: python train_model.py --net_type Unet --backbone efficientnetb0 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 5e-4 --dataset cyc2_1488x1512 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_model.py --net_type Unet --backbone efficientnetb1 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 5e-4 --dataset cyc2_1488x1512 --gpu 1 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_model.py --net_type Unet --backbone efficientnetb2 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 5e-4 --dataset cyc2_1488x1512 --gpu 2 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4
# JOB: python train_model.py --net_type Unet --backbone efficientnetb3 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 5e-4 --dataset cyc2_1488x1512 --gpu 3 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4

# JOB: python train_viability.py --net_type Unet --backbone efficientnetb0 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 5e-4 --dataset viability2_832x832 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb1 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 5e-4 --dataset viability2_832x832 --gpu 1 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb2 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 5e-4 --dataset viability2_832x832 --gpu 2 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb3 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 5e-4 --dataset viability2_832x832 --gpu 3 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4

# Jan 20, 2021
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb0 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability2_832x832 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb1 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability2_832x832 --gpu 1 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb2 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability2_832x832 --gpu 2 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb3 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability2_832x832 --gpu 3 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4

# JOB: python train_viability.py --net_type Unet --backbone efficientnetb4 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability2_832x832 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb5 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability2_832x832 --gpu 1 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb6 --pre_train True --batch_size 3 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability2_832x832 --gpu 2 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb7 --pre_train True --batch_size 2 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability2_832x832 --gpu 3 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4

# JOB: python train_viability.py --net_type AtUnet --backbone efficientnetb0 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability2_832x832 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type AtUnet --backbone efficientnetb1 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability2_832x832 --gpu 1 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type AtUnet --backbone efficientnetb2 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability2_832x832 --gpu 2 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4
# JOB: python train_viability.py --net_type AtUnet --backbone efficientnetb3 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability2_832x832 --gpu 3 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4

# Jan 21, 2021
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb0 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability2_832x832 --data_version 3 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb1 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability2_832x832 --data_version 3 --gpu 1 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb2 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability2_832x832 --data_version 3 --gpu 2 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb3 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability2_832x832 --data_version 3 --gpu 3 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4

# JOB: python train_viability.py --net_type Unet --backbone efficientnetb4 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability2_832x832 --data_version 3 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb5 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability2_832x832 --data_version 3 --gpu 1 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb6 --pre_train True --batch_size 3 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability2_832x832 --data_version 3 --gpu 2 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb7 --pre_train True --batch_size 2 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability2_832x832 --data_version 3 --gpu 3 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4

# JOB: python train_model.py --net_type Unet --backbone efficientnetb4 --pre_train True --batch_size 4 --dim 800 --epoch 4800 --lr 1e-4 --dataset cyc2_1488x1512 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_model.py --net_type Unet --backbone efficientnetb5 --pre_train True --batch_size 4 --dim 800 --epoch 4800 --lr 1e-4 --dataset cyc2_1488x1512 --gpu 1 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 0.8 --bk 1.0 --focal_weight 4 
# JOB: python train_model.py --net_type Unet --backbone efficientnetb6 --pre_train True --batch_size 3 --dim 800 --epoch 4800 --lr 1e-4 --dataset cyc2_1488x1512 --gpu 2 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4
# JOB: python train_model.py --net_type Unet --backbone efficientnetb7 --pre_train True --batch_size 2 --dim 800 --epoch 4800 --lr 1e-4 --dataset cyc2_1488x1512 --gpu 3 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4

# Feb 4, 2021
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb4 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability3_800x800 --data_version 0 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb5 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability3_800x800 --data_version 0 --gpu 1 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb6 --pre_train True --batch_size 3 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability3_800x800 --data_version 0 --gpu 2 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb7 --pre_train True --batch_size 2 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability3_800x800 --data_version 0 --gpu 3 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4

# JOB: python train_viability.py --net_type Unet --backbone efficientnetb6 --pre_train True --batch_size 3 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability3_800x800 --data_version 0 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb4 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability3_800x800 --data_version 0 --gpu 1 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb3 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability3_800x800 --data_version 0 --gpu 2 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb2 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability3_800x800 --data_version 0 --gpu 3 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4

# Feb 9, 2021
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb6 --pre_train True --batch_size 3 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability_c_800x800 --data_version 0 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb5 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability_c_800x800 --data_version 0 --gpu 1 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb4 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability_c_800x800 --data_version 0 --gpu 2 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb7 --pre_train True --batch_size 2 --dim 800 --epoch 2400 --lr 1e-4 --dataset viability_c_800x800 --data_version 0 --gpu 3 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4

# Feb 12, 2021
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb6 --pre_train True --batch_size 3 --dim 800 --epoch 2400 --lr 3e-5 --dataset viability_c_800x800 --data_version 0 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb5 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 3e-5 --dataset viability_c_800x800 --data_version 0 --gpu 1 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb4 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 3e-5 --dataset viability_c_800x800 --data_version 0 --gpu 2 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4
# JOB: python train_viability.py --net_type Unet --backbone efficientnetb7 --pre_train True --batch_size 2 --dim 800 --epoch 2400 --lr 3e-5 --dataset viability_c_800x800 --data_version 0 --gpu 3 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4

JOB: python train_viability.py --net_type Unet --backbone efficientnetb0 --pre_train True --batch_size 6 --dim 800 --epoch 2400 --lr 3e-5 --dataset viability_c_800x800 --data_version 0 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
JOB: python train_viability.py --net_type Unet --backbone efficientnetb1 --pre_train True --batch_size 6 --dim 800 --epoch 2400 --lr 3e-5 --dataset viability_c_800x800 --data_version 0 --gpu 1 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4 
JOB: python train_viability.py --net_type Unet --backbone efficientnetb2 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 3e-5 --dataset viability_c_800x800 --data_version 0 --gpu 2 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4
JOB: python train_viability.py --net_type Unet --backbone efficientnetb3 --pre_train True --batch_size 4 --dim 800 --epoch 2400 --lr 3e-5 --dataset viability_c_800x800 --data_version 0 --gpu 3 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 1.0 --bk 1.0 --focal_weight 4