## June 18
# python live_dead.py --net_type FPN --backbone efficientnetb3 --pre_train True --batch_size 8 --dim 320 --epoch 600 --lr 5e-4 --gpu 0

# python live_dead.py --net_type Unet --backbone efficientnetb3 --pre_train True --batch_size 5 --dim 512 --epoch 200 --lr 5e-4 --train 900 --bk_weight 0.7 --gpu 0
# python live_dead.py --net_type Unet --backbone efficientnetb3 --pre_train True --batch_size 5 --dim 512 --epoch 300 --lr 5e-4 --dataset live_dead_1664 --train 900 --rot 0 --gpu 0
# python live_dead.py --net_type Unet --backbone efficientnetb3 --pre_train True --batch_size 5 --dim 416 --epoch 100 --lr 5e-4 --dataset live_dead --down_factor 2 --train 900 --rot 45 --gpu 0

# python live_dead.py --net_type Unet --backbone efficientnetb3 --pre_train True --batch_size 5 --dim 512 --epoch 200 --lr 5e-4 --dataset live_dead --down_factor 1 --train 900 --gpu 0 --loss focal+dice
# python life_cycle_flu.py --net_type Unet --backbone efficientnetb3 --pre_train True --batch_size 1 --dim 1024 --epoch 60 --lr 5e-4 --train 1100 --filtered True --gpu 0 --loss mse --act_fun relu --channels fl1
# python cell_cycle.py --net_type Unet --backbone efficientnetb3 --pre_train True --batch_size 1 --dim 1024 --down_factor 1 --epoch 100 --dataset cell_cycle_1984_v2 --lr 5e-4 --train 1100 --gpu 3 --loss focal+dice
# python life_cycle_flu.py --net_type Unet --backbone efficientnetb3 --pre_train True --batch_size 1 --dim 1024 --epoch 100 --lr 5e-4 --train 1100 --filtered False --gpu 0 --loss mse --act_fun relu --channels fl1 --dataset cell_cycle_1984_v2 --flu_scale 1.0
# python cell_cycle.py --net_type Unet --backbone efficientnetb3 --pre_train True --batch_size 1 --dim 1024 --down_factor 1 --ext True --epoch 100 --dataset cell_cycle_1984_v2 --lr 5e-4 --train 1100 --gpu 0 --loss focal+dice
#python phase_flu.py --net_type Unet --backbone efficientnetb3 --pre_train True --batch_size 2 --dim 800 --epoch 60 --lr 5e-4 --train 1100 --filtered True --gpu 0 --loss mse --act_fun sigmoid --channels fl1 --dataset cell_cycle_1984 --ext False
# python deeply_train.py --net_type DUNet --backbone efficientnetb3 --pre_train True --batch_size 4 --dim 512 --epoch 1 --lr 5e-4 --dataset live_dead --train 900 --gpu 1 --loss focal+dice
# python single_train.py --net_type FPN --backbone efficientnetb2 --pre_train True --batch_size 4 --dim 512 --epoch 1 --lr 5e-4 --dataset live_dead --train 900 --gpu 0 --loss focal+dice
# python single_train.py --net_type BiFPN --backbone efficientnetb0 --pre_train True --batch_size 4 --dim 512 --epoch 1 --lr 5e-4 --dataset live_dead --train 900 --gpu 0 --loss focal+dice
# python single_train.py --net_type BiFPN --backbone efficientnetb0 --pre_train True --batch_size 4 --dim 512 --epoch 1 --lr 5e-4 --dataset live_dead --train 900 --gpu 0 --loss focal+dice
# python single_train.py --net_type Nestnet --backbone efficientnetb3 --pre_train True --batch_size 2 --dim 512 --epoch 60 --lr 5e-4 --dataset live_dead --train 900 --gpu 0 --loss focal+dice
# python phase_flu.py --net_type Unet --backbone efficientnetb3 --pre_train True --batch_size 2 --dim 800 --epoch 60 --lr 5e-4 --train 1100 --filtered True --gpu 0 --loss mse+focal --act_fun sigmoid --channels fl1 --dataset cell_cycle_1984 --ext False
# python single_train.py --net_type Unet --backbone efficientnetb0 --pre_train True --batch_size 2 --dim 800 --epoch 150 --lr 5e-4 --dataset live_dead --train 900 --gpu 0 --loss focal+dice --filters 512 --upsample upsampling
# python phase_fl_train.py --net_type Unet --backbone efficientnetb3 --pre_train True --batch_size 2 --dim 800 --epoch 60 --lr 5e-4 --train 1100 --filtered True --gpu 0 --loss wmse --act_fun sigmoid --channels fl1 --dataset cell_cycle_1984 --ext False --gt_weight 0.2
# python single_train.py --net_type ResUnet --backbone efficientnetb3 --pre_train True --batch_size 4 --dim 512 --epoch 150 --lr 5e-4 --dataset live_dead --train 900 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling
# python single_train_v2.py --net_type Unet --backbone efficientnetb3 --pre_train True --batch_size 8 --dim 256 --epoch 1 --lr 5e-4 --dataset cell_cycle_1984 --train 1100 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling
# python single_train_v4.py --net_type Unet --backbone efficientnetb0 --pre_train True --batch_size 2 --dim 1024 --epoch 1 --lr 5e-4 --dataset cell_cycle_1984_v2 --ext True --train 1100 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling --reduce_factor 0.8 --bk 1.0 --focal_weight 4 --feat_version 1
python single_train_v5.py --net_type Unet --backbone efficientnetb6 --pre_train True --batch_size 1 --dim 800 --epoch 1200 --lr 5e-4 --dataset cell_cycle_1984_v2 --ext True --train 1100 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling --ext True --reduce_factor 1.0 --bk 1.0 --focal_weight 4 --feat_version 1
python single_train_v5.py --net_type Unet --backbone efficientnetb7 --pre_train True --batch_size 1 --dim 640 --epoch 1200 --lr 5e-4 --dataset cell_cycle_1984_v2 --ext True --train 1100 --gpu 2 --loss focal+dice --filters 256 --upsample upsampling --ext True --reduce_factor 1.0 --bk 1.0 --focal_weight 4 --feat_version 1
python single_train_v5.py --net_type Unet --backbone efficientnetb3 --pre_train True --batch_size 2 --dim 800 --epoch 1200 --lr 5e-4 --dataset cell_cycle_1984_v2 --ext True --train 1100 --gpu 0 --loss focal+dice --filters 256 --upsample upsampling --ext True --reduce_factor 1.0 --bk 1.0 --focal_weight 4 --feat_version 1
python single_train_v5.py --net_type Unet --backbone efficientnetb4 --pre_train True --batch_size 2 --dim 640 --epoch 1200 --lr 5e-4 --dataset cell_cycle_1984_v2 --ext True --train 1100 --gpu 1 --loss focal+dice --filters 256 --upsample upsampling --ext True --reduce_factor 1.0 --bk 1.0 --focal_weight 4 --feat_version 1